//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStagiaires.Stagiaires {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StagiaireEntryForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StagiaireEntryForm() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionStagiaires.Stagiaires.StagiaireEntryForm", typeof(StagiaireEntryForm).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool adressLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("adressLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool cinLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("cinLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool dateNaissanceLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("dateNaissanceLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool emailLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("emailLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point filiereBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("filiereBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=177,Y=17}.
        /// </summary>
        internal static System.Drawing.Point groupeBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("groupeBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool nomLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("nomLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool prenomLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("prenomLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à False.
        /// </summary>
        internal static bool telephoneLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("telephoneLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
