// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_GestionPorjet_Required_Titre_Tache : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_GestionPorjet_Required_Titre_Tache));
        
        string IMigrationMetadata.Id
        {
            get { return "201701160810316_Update_GestionPorjet_Required_Titre_Tache"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
